apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: app-subnet1
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    cidrBlock: 10.0.1.0/24
    vpcIdRef:
      name: app-vpc
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: app-subnet2
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1b
    cidrBlock: 10.0.2.0/24
    vpcIdRef:
      name: app-vpc
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: aws-provider