
apiVersion: secretsmanager.aws.crossplane.io/v1beta1
kind: Secret
metadata:
  name: main-app-secrets
spec:
  forProvider:
    region: us-east-1
    description: "This secret is going to be used on k8s cluster"
    forceDeleteWithoutRecovery: true
    stringSecretRef:
      name: main-app-secrets
      namespace: crossplane-system
    tags:
      - key: secret
        value: "Main app Secret"
  providerConfigRef:
    name: aws-provider
---
apiVersion: v1
kind: Secret
metadata:
  name: main-app-secrets
  namespace: crossplane-system
type: Opaque
data:
    username: dXNlcg== #user
    password: cGFzc3dvcmQ= #password
    endpoint: bXlzcWwtc3Zj #mysql-svc
