apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider
spec:
  provider: aws  
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: "MySecretPassword"
          key: password
        - objectName: "MySecretUsername"
          key: username    
        - objectName: "MySecretEndpoint"
          key: endpoint        
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:us-east-1:<ACCOUNT_ID>:secret:main-app-secrets-#### #SecretARN
        jmesPath:
            - path: "username"
              objectAlias: "MySecretUsername"
            - path: "password"
              objectAlias: "MySecretPassword"
            - path: "endpoint"
              objectAlias: "MySecretEndpoint"