apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider
spec:
  provider: aws      
  parameters:
    objects: |
      - objectName: arn:*:secretsmanager:*:*:secret:main-app-secrets
        jmesPath:
            - path: "username"
              objectAlias: "main-app-secrets"
            - path: "password"
              objectAlias: "main-app-secrets"
            - path: "endpoint"
              objectAlias: "main-app-secrets"